# requires synced folder generated by peakCVSyncVid with subs folders containing nucs and their frames
# and the groups.csv
# This code is partilly written with the help of AI.

import os
import argparse
import numpy as np
import pandas as pd
from tqdm import tqdm
from ultralytics import YOLO


MODEL = "yolo11x-pose.pt" # or every other yolo model
IMGSZ = 1280  # image size YOLO works with


def read_groups(synced_dir):
    '''
    Reads groups.csv (made by sync_frames.py).

    :param synced_dir: synced folder (e.g. recordings/test/synced)
    :return: dataframe of groups.csv, list of camera names, times in seconds since the first frame
    '''
    path = os.path.join(synced_dir, "groups.csv")
    if not os.path.exists(path):
        raise FileNotFoundError(f"{path} not found. Run sync_frames.py first.")

    df = pd.read_csv(path)

    # first two columns are index and time_ns, the others are the cameras
    cameras = list(df.columns[2:])

    t = df["time_ns"].to_numpy(dtype=np.int64)
    times = (t - t[0]) / 1e9

    return df, cameras, times


def detect(synced_dir):
    '''
    Runs YOLO on all synced images and saves the keypoints in keypoints2d.npz.

    :param synced_dir: synced folder (e.g. recordings/test/synced)
    '''
    print('------------------ 2D POSE ESTIMATION -------------------')

    df, cameras, times = read_groups(synced_dir)
    print(f"{len(df)} time points, cameras: {', '.join(cameras)}")

    model = YOLO(MODEL)

    # NaN = no person found
    keypoints = np.full((len(df), len(cameras), 17, 3), np.nan, np.float32)

    for i in tqdm(range(len(df)), desc="Detecting poses"):
        index = int(df["index"].iloc[i])

        # images of all cameras of this time point
        paths = []
        for cam in cameras:
            paths.append(os.path.join(synced_dir, cam, f"{index:06d}.png"))

        results = model.predict(paths, imgsz=IMGSZ, quantize=16, verbose=False)

        for v in range(len(results)):
            r = results[v]
            if len(r.boxes) > 0:
                # only one person: take the most confident detection
                best = int(r.boxes.conf.argmax())
                keypoints[i, v] = r.keypoints.data[best].cpu().numpy()

    out_path = os.path.join(synced_dir, "keypoints2d.npz")
    np.savez_compressed(out_path, cameras=cameras, times=times, keypoints=keypoints)

    for v in range(len(cameras)):
        found = np.mean(~np.isnan(keypoints[:, v, 0, 2])) * 100
        print(f"{cameras[v]}: person found in {found:.1f} % of the frames")

    print(f"keypoints2d.npz has been written to {out_path}")
    print('---------------------------------------------------------')


def main():
    parser = argparse.ArgumentParser(description="2D pose estimation")
    parser.add_argument("synced_dir", type=str, nargs="?", help="e.g. recordings/test/synced")
    args = parser.parse_args()

    # Interactive fallback
    if args.synced_dir is None:
        args.synced_dir = input("Synced folder (e.g. recordings/test/synced): ").strip()

    detect(args.synced_dir)


# python3 detect_2d.py recordings/test/synced

if __name__ == "__main__":
    main()